- README.md
- package.json
express-openapi-coercion now supports `formData` and `collectionFormat`
> New express-openapi-coercion version

- index.js
- test/sample-projects.js
- test/sample-projects/with-apiDoc-as-array-method-handler-property/api-doc.js
- test/sample-projects/with-apiDoc-as-array-method-handler-property/api-routes/users.js
- test/sample-projects/with-apiDoc-as-array-method-handler-property/api-routes/users/{id}.js
- test/sample-projects/with-apiDoc-as-array-method-handler-property/app.js
- typings/express-openapi/express-openapi.d.ts
Allow method doc as REDME style when method handler is Array as in README.
Following style is used in README.
```javascript
module.exports.post = [function (res, req, next) { next();}, post];
function post(res, req, next) { res.status(200}.json({message:'ok'});}
module.exports.post.apiDoc = {
// api doc here
};
```
On the other hand, implementation and test uses this:
```javascript
module.exports.post = [function (res, req, next) { next();}, post];
function post(res, req, next) { res.status(200}.json({message:'ok'});}
post.apiDoc = {
// api doc here
};
```
This PR allows both style. And for BC, latter style has priority.
> Fix method doc loading

- index.js
- test/initialization.js
- test/sample-projects.js
- test/sample-projects/with-apiDoc-parameters-and-responses/api-doc.js
- test/sample-projects/with-apiDoc-parameters-and-responses/api-routes/foo.js
- test/sample-projects/with-apiDoc-parameters-and-responses/app.js
- test/sample-projects/with-referenced-parameter-missing/api-doc.js
- test/sample-projects/with-referenced-parameter-missing/api-routes/foo.js
- test/sample-projects/with-referenced-parameter-missing/app.js
- test/sample-projects/with-referenced-response-missing/api-doc.js
- test/sample-projects/with-referenced-response-missing/api-routes/foo.js
- test/sample-projects/with-referenced-response-missing/app.js
* Supporting  in parameters and responses.
* Only supporting local references at this time to avoid async operations.
* Bumping coverage back up.
* Adding a warning message in the console for $ref: #/definitions/... in responses object.
> 	partial fix for #17: Support external schema reference. 

- index.js
Maybe, `gument` is inserted accidentally unless it is a new word such as even google doesn't know.
> Fix typo in comment

- typings/express-openapi/express-openapi.d.ts
- now externalDocs and example is optional
> Fix type definition of `Schema Object` for typescript

- index.js
- test/sample-projects.js
- test/sample-projects/with-express-mount-after-initialize/api-doc.js
- test/sample-projects/with-express-mount-after-initialize/api-routes/foo.js
- test/sample-projects/with-express-mount-after-initialize/app.js
- test/sample-projects/with-express-mount-before-initialize/api-doc.js
- test/sample-projects/with-express-mount-before-initialize/api-routes/foo.js
- test/sample-projects/with-express-mount-before-initialize/app.js
refs https://github.com/kogosoftwarellc/express-openapi/issues/3#issuecomment-199412051
```js
var parentApp = express();
var app = express();
parentApp.use('/api', app);
openapi.initialize({
app: app,
apiDoc: require('./apiDoc.js'), // basePath = '/v1'
routes: './routes'
});
// you can also mount here
// parentApp.use('/api', app);
```
Then apiDoc.basePath is `/api/v1`.
> Support express mount app

- typings/express-openapi/express-openapi.d.ts
> Fix typo in type definition for typescript

- README.md
- Change definition manager to `typings` because `tsd` is deprecated
- Fix typo in example
> Update typescript section of readme

- typings/express-openapi/express-openapi.d.ts
`request.get()`, `request.header()`, `request.headers[]` may not returns string only.
because:
https://github.com/kogosoftwarellc/express-openapi-coercion/blob/33a4bdbf95b26675e26db8c4b80ad5a3abc9a013/index.js#L41-L80
> Typing: Fix `Request` interface to follow coercion result.

- typings/express-openapi/express-openapi.d.ts
> Update type definition for typescript to allow openapi extended schema

- index.js
- test/sample-projects.js
- test/sample-projects/with-express-mount-deeply-nested/api-doc.js
- test/sample-projects/with-express-mount-deeply-nested/api-routes/foo.js
- test/sample-projects/with-express-mount-deeply-nested/app.js
- test/sample-projects/with-express-mount-on-router/api-doc.js
- test/sample-projects/with-express-mount-on-router/api-routes/foo.js
- test/sample-projects/with-express-mount-on-router/app.js
Handle nested apps (see issue #40) by updating the basePath when the apiDoc is requested.
> Update basePath at request time.

- package.json
Hi!
Bumping the version for express-openapi-validation: See https://github.com/kogosoftwarellc/express-openapi-validation/pull/4
Thanks!
> Bump express-openapi-validation version in package.json

- index.d.ts
I'm not 100% about this, but I get an error when using the middleware in typescript and adding this line removes the error.
> Allow the case insensitive middleware to be added

- index.js
I have following routes:
pathx/{id}
pathx/latest
And it seems that the dynamic pathx/{id} currently takes precedence, over the static pathx/latest, which might not be desired?
> Static routes before dynamic routes

- README.md
Just a small correction of a link in README.md
> Fixed "Using with TypeScript"-Link

- packages/express-openapi/index.js
> express-openapi: Only add basePath, host to apiDoc if swagger document. (fixes #142)

- packages/express-openapi/index.d.ts
TypeScript definitions were missing `paths` objects, `routesGlob`, and `indexFileRegExp`.
> [express-openapi] Add alternative routes/paths specifications to definitions

- packages/openapi-types/index.ts
Now that the openapi attribute distinguishes v2 from v3, here are the types that belong to it.
> [openapi-types]: Fill out the OpenAPI v3 Typescript types

- packages/openapi-jsonschema-parameters/index.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-nullable-query-param-to-json-schema-openapi3.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-multiple-basic-query-params-to-json-schema-openapi3.js
- packages/openapi-jsonschema-parameters/test/data-driven/handle-some-required-query-params-openapi3.js
OpenAPI 3 moved query parameter schemas under their own schema object, see the [parameter object](https://swagger.io/specification/#parameterObject) specification.
> Fix: Request validator does not validate query params in OpenAPI 3

- packages/openapi-request-validator/test/data-driven/accept-custom-formats-openapi3.js
- packages/openapi-request-validator/test/data-driven/fail-customFormats-for-openapi3-query-param.js
Just a test for openapi-request-validator corresponding to the fix in openapi-jsonschema-parameters. Probably not ready to be merged until the greenkeeper package update lands.
> Add test for OpenAPI 3 query parameters

- packages/openapi-types/index.ts
My typescript project wouldn't compile without casting my schema types as "string" | "number" | "boolean" | "object" | "integer" | "null". I created a type to match the one correct string literal locally but this way we can export the correct types in case the spec changes.
> export SchemaObject "type" property type

- packages/openapi-request-validator/README.md
- packages/openapi-request-validator/index.js
- packages/openapi-request-validator/package-lock.json
- packages/openapi-request-validator/package.json
- packages/openapi-request-validator/test/data-driven/fail-a-missing-required-body-property.js
- packages/openapi-request-validator/test/data-driven/fail-a-missing-required-formData-property.js
- packages/openapi-request-validator/test/data-driven/fail-a-missing-required-header-param.js
- packages/openapi-request-validator/test/data-driven/fail-a-missing-required-query-param.js
- packages/openapi-request-validator/test/data-driven/fail-an-invalid-path-param.js
- packages/openapi-request-validator/test/data-driven/fail-an-unknown-ref-in-body.js
- packages/openapi-request-validator/test/data-driven/fail-body-expecting-array.js
- packages/openapi-request-validator/test/data-driven/fail-customFormats-for-openapi3-query-param.js
- packages/openapi-request-validator/test/data-driven/fail-customFormats.js
- packages/openapi-request-validator/test/data-driven/fail-external-ref-in-body.js
- packages/openapi-request-validator/test/data-driven/fail-external-ref-through-local-ref-in-body.js
- packages/openapi-request-validator/test/data-driven/fail-missing-path-params.js
- packages/openapi-request-validator/test/data-driven/fail-multiple-invalid-path-params.js
- packages/openapi-request-validator/test/data-driven/fail-multiple-local-refs-in-body.js
- packages/openapi-request-validator/test/data-driven/fail-multiple-missing-local-refs-in-body.js
- packages/openapi-request-validator/test/data-driven/fail-recursive-ref-in-body-as-object.js
- packages/openapi-request-validator/test/data-driven/fail-schema-ref-in-body.js
We have started to use this library for some of our production services, and during profiling we noticed that a large amount of the processing time for requests was being spent validating incoming requests.
To improve this situation, I have ported `openapi-request-validator` to use [`ajv`](https://ajv.js.org/) rather than `jsonschema`. In many cases this change results in speed-ups of 1-3 orders of magnitude, especially with more complex schemas involved.
I have run all positive test cases as benchmarks using the old and the new code, and published a gist with the raw results here: https://gist.github.com/srijs/b6d6e01931d6fe20d65c90f6d275f35c
The main reason `ajv` achieves these speed-ups is that it compiles the schema eagerly into a validation function, rather than interpreting the …
> openapi-request-validator: use ajv instead of jsonschema for validation

- packages/openapi-response-validator/README.md
- packages/openapi-response-validator/index.js
- packages/openapi-response-validator/package-lock.json
- packages/openapi-response-validator/package.json
- packages/openapi-response-validator/test/data-driven/fail-any-response-with-undefined-schema.js
- packages/openapi-response-validator/test/data-driven/fail-customFormats.js
- packages/openapi-response-validator/test/data-driven/fail-invalid-response.js
- packages/openapi-response-validator/test/data-driven/fail-response-against-undefined-schema.js
- packages/openapi-response-validator/test/data-driven/fail-unexpected-empty-response.js
- packages/openapi-response-validator/test/data-driven/fail-with-definition-references.js
- packages/openapi-response-validator/test/data-driven/fail-with-external-references-through-local-ref.js
- packages/openapi-response-validator/test/data-driven/fail-with-external-references-with-path-through-local-ref.js
- packages/openapi-response-validator/test/data-driven/fail-with-external-references-with-path.js
- packages/openapi-response-validator/test/data-driven/fail-with-external-references.js
Follow up from #161.
This is a breaking change again due to mapping through the underlying validation errors.
> openapi-response-validator: use ajv instead of jsonschema for validation

- packages/express-openapi/index.d.ts
This is to make sure we don't forget to change the type definitions for `express-openapi` when we cascade the ajv changes. Feel free to cherry-pick this commit into your own branch when you bump the versions!
> express-openapi: fix type definitions for ajv error

- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/coerce-object-params-in-request.js
openapi-request-coercer: added initial support for type object coercion using the format property as a strategy setting
> openapi-request-coercer: support to type object coercion

- packages/express-openapi/package-lock.json
- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/coerce-array-with-style-openapi3.js
- packages/openapi-request-coercer/test/data-driven/coerce-boolean-params-invalid-value-openapi3.js
- packages/openapi-request-coercer/test/data-driven/coerce-boolean-params-openapi3.js
- packages/openapi-request-coercer/test/data-driven/coerce-object-params-in-request-openapi3.js
- packages/openapi-request-coercer/test/data-driven/coerce-params-in-request-openapi3.js
- packages/openapi-request-coercer/test/data-driven/handle-strict-extension-openapi3.js
- packages/openapi-request-coercer/test/data-driven/ignore-object-params-in-request-when-enableObjectCoercion-is-not-set-openapi3.js
- packages/openapi-request-coercer/test/data-driven/ignore-unkown-types-openapi3.js
- packages/openapi-request-coercer/test/data-driven/should-pass-through-arrays-openapi3.js
- packages/openapi-request-coercer/test/data-driven/throw-error-when-array-parameter-has-items-property-of-type-array-openapi3.js
- packages/openapi-request-coercer/test/data-driven/throw-error-when-array-parameter-has-no-items-property-openapi3.js
Request validation is failing on any non-string query parameter if OpenAPI 3 specification is used because coercion is not occurring. The [parameter specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject) changed so a schema property now holds most of the type related information for the coercer to work properly.
A second change is the removal of the collectionFormat property from the parameter specification. It was replaced with a combination of `in`, `style` and `explode` properties. This PR also addresses that change.
I tried to write tests mimicking the existing test suite with OpenAPI 3 parameter specifications and added a test to validate the collectionFormat change.
> openapi-request-coercer: add OpenAPI3 support to coercer

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/package-lock.json
- packages/openapi-response-validator/test/data-driven/accept-nullable-properties.js
test case shows error and fails but shouldn't in openapi v3
> openapi-response-validator: now accepts nullable property + test

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/package-lock.json
- packages/openapi-response-validator/test/data-driven/accept-openapi3-responses.js
it fails now since validator doesn't find schema in responses.200.schema but it is in responses.200.content.application/json.schema
> openapi-response-validator: accepts openapi3 response

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/accept-openapi3-with-ref-responses.js
Following discussion in #269, creating this PR.
Fixed an issue with openapi schemas with references.
I believe fix is slightly sloppy, because it mixes v2 and v3 specific fields in code. 
Would be nice to refactor code, so it would be easier to implement specific behaviour for specific version of the schema.
> fix: Fix OpenAPI v3 response validation for schemas with references

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/accept-openapi3-responses-different-content-types.js
> openapi-response-validator: Allow different content types for OpenAPI 3.0 response definitions

- packages/openapi-framework/index.ts
- packages/openapi-framework/src/BasePath.ts
- packages/openapi-framework/src/types.ts
- packages/openapi-framework/src/util.ts
- packages/openapi-framework/test/sample-projects/base-paths/spec.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-doc-default-parameters-disabled/spec.ts
OpenAPI v3 support for openapi-framework.  Note that I'm replacing basePath with basePaths so this will be a breaking change.
After this is published I can make the `express-openapi` and `koa-openapi` pull requests.
> openapi-framework: OpenApi v3 servers support

- packages/express-openapi/index.ts
- packages/express-openapi/package-lock.json
- packages/express-openapi/package.json
- packages/express-openapi/test/sample-projects/with-servers/api-routes/users.js
- packages/express-openapi/test/sample-projects/with-servers/spec.js
- packages/koa-openapi/index.ts
- packages/koa-openapi/package-lock.json
- packages/koa-openapi/package.json
- packages/koa-openapi/test/sample-projects/with-servers/api-routes/users.js
- packages/koa-openapi/test/sample-projects/with-servers/spec.js
`express-openapi` and `koa-openapi` now take advantage of new basePaths attribute from `openapi-framework` which is derived from either the basePath attribute in openapi v2 or the servers attribute from openapi v3.  
Closes #274
> Express koa openapiv3 servers

- packages/openapi-response-validator/index.ts
Previously, the response validator would mutate properties in the api doc where nullable: true for openapi v3 docs. For example,  ```{ name: {type: "string", nullable: true}}``` would become ```{ name: {type: ["string", null]}}```, so when the framework tries to validate the doc after populating paths, it would fail validation. Now  that schema is deep copied with lodash.clonedeep as opposed to shallow copied with the spread operator, the api doc doesn't mutate and stays valid after passing through the response validator.
> openapi-response-validator: Deep clone schemas before transforming nullable values.

- packages/openapi-framework/index.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-security-and-securityHandlers-and-securityDefinitions-in-openapi-3/apiDoc.yml
- packages/openapi-framework/test/sample-projects/paths-dir-with-security-and-securityHandlers-and-securityDefinitions-in-openapi-3/paths/foo.js
- packages/openapi-framework/test/sample-projects/paths-dir-with-security-and-securityHandlers-and-securityDefinitions-in-openapi-3/spec.ts
For context, see #305 and #259 
Based on @jwmur's work in #259.
@jsdevel Let me know if you need me to fix anything in this PR or add any tests etc.
Thanks!
> Fixes support for args.securityHandlers in OpenApi 3

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/fail-bad-media-type-for-request-body.js
- packages/openapi-request-validator/test/data-driven/handle-missing-content-type-as-missing-body.js
`OpenAPIRequestValidator.validate(request)` currently fails with `TypeError` if `Content-Type` header is missing or invalid and `requestBody` is defined in schema.
This PR makes it return `415 Unsupported Media Type` on invalid `Content-Type` and `400 Bad Request` if `Content-Type` is missing but required by `requestBody`.
> openapi-request-validator: Handle missing or invalid 'Content-Type'

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/accept-valid-wildcard-responses.js
accept ?XX style status codes as allowed by openapi specification -- https://swagger.io/specification/#responsesObject
> accept ?XX style status codes

- packages/openapi-types/index.ts
Specification allows arbitrary names for security schemes,
but current types restrict it to 4 hard-coded values.
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-requirement-object
> openapi-types: relax security requirement object types

- packages/openapi-framework/index.ts
- packages/openapi-framework/test/sample-projects/operations-dir-multiple-methods/apiDoc.yml
- packages/openapi-framework/test/sample-projects/operations-dir-multiple-methods/operations/foo.js
- packages/openapi-framework/test/sample-projects/operations-dir-multiple-methods/spec.ts
This initially implements a different approach for `args.operations` handling so that it's easier to handle multiple methods per path, which is not fully working as per #352.
Current issue is mainly with tests `operations-dir-with-overlap` and `operations-dir`, which have overlapping/duplicated routes due to `paths` and `operations` being used at the same time. What should be the behavior for those cases?
> feat: different approach to handle operations in openapi-framework initialization

- packages/express-openapi/README.md
- packages/openapi-framework/index.ts
- packages/openapi-framework/test/sample-projects/operations-dir-with-valid-methid-doc-after-dependency-injection/apiDoc.yml
- packages/openapi-framework/test/sample-projects/operations-dir-with-valid-methid-doc-after-dependency-injection/operations/foo.js
- packages/openapi-framework/test/sample-projects/operations-dir-with-valid-methid-doc-after-dependency-injection/spec.ts
Inject dependencies on operations by the means of binding the operation handlers so that they get `this.dependencies`
> Dependency injection for operations

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-no-parameters.js
The request validation feature now can be used without define parameters, since requestBody is also valid by his own
Closes #381
> openapi-request-validator: Allow to use request validation without parameters

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-ref.js
Fix for when a requestBody is missing a required and readOnly parameter in a referenced schema. Only affects referenced schemas and OpenAPI3.
> Accept a requestBody with missing readOnly required property in ref (fixes #389)

- packages/express-openapi/README.md
The `x-express-openapi-additional-middleware` setting is on the `apiDoc`.
> Correct example for validating all responses

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-allOf.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-anyOf.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-array.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-nested-refs.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-oneOf.js
- packages/openapi-request-validator/test/data-driven/fail-request-body-when-oneOf-meets-multiple-schemas.js
- packages/openapi-request-validator/test/data-driven/fail-requestBody-with-required-readOnly-property-value-false.js
Some insight:
- Allows required properties to be missing from requestBody if readOnly
- Works with nested ref
- Works with array where items are ref
- Works with AllOf, AnyOf and OneOf
- Adds tests
I've achieved this within the request-validator package by cloning the schemas, resolving refs and removing all instances of readOnly properties from the required array of their respective schemas.
Edit: Clarity
> openapi-request-validator: accept reqBody RO nested ref (fixes #394)

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/accept-valid-responses-with-defaults.js
> openapi-response-validator: Set "useDefaults: true" on Ajv

- packages/express-openapi/README.md
Supported Versions of Node was linking to incorrect anchor in express-openapi/README.md
> Fix broken link in express-openapi/README.md

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-nullable-and-type-on-allOf.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-nullable-enum.js
- Allow nullable and null enums on the request validation
Closes #397
> feat(openapi-request-validator): allow null enums and nullable option

- packages/openapi-types/index.ts
Amend missing usage of PathsObject in OpenAPIV3.Document interface.
> openapi-types: use PathsObject correctly in v3 Document

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/accept-null-examples.js
The `recursiveTransformOpenAPIV3Definitions()` function ironically does
not take into accout that `typeof null == 'object'`. This was causing it
to attempt to transform `null` which results in `TypeError`.
Fixes #413
> Correct nullable transform for null examples

- packages/openapi-framework/index.ts
- packages/openapi-framework/test/sample-projects/missing-operation-id/apiDoc.yml
- packages/openapi-framework/test/sample-projects/missing-operation-id/spec.ts
One new test. I opted to change just the warning and not the exception. If you feel that the exception should be changed as well, then an additional guard clause will need to be inserted.
> openapi-framework: Log an improved warning if the operationId of an operation is not specified (fixes #465)

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-deeply-nested.js
Hi,
#400 fixed the nested readOnly behaviour for all schemas with refs. But if you are not using refs for nested properties, it will not allow you to use readOnly properties correctly.
This change will call the sanitize function and itself (recursive) for all properties inside the current schema. The recursive call will ensure that all nested properties are resolved and sanitized, no matter how deep they are nested.
Thanks for maintaining this project! ❤️
> openapi-request-validator: accept reqBody readOnly in nested properties

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/accept-responseBody-with-missing-writeonly-required-property-allOf.js
- packages/openapi-response-validator/test/data-driven/accept-responseBody-with-missing-writeonly-required-property-anyOf.js
- packages/openapi-response-validator/test/data-driven/accept-responseBody-with-missing-writeonly-required-property-oneOf.js
- packages/openapi-response-validator/test/data-driven/accept-responseBody-with-missing-writeonly-required-property.js
Almost the same as #472 but now for props which are marked as required and `writeOnly`.
As defined [here](https://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3) this allows to defined props which are required in the request, but must not be part of the response.
_Note_: For now there is no validation if the defined props is really not part of the response, it only removes them from the required array (in response validation). The same problem applies in the `request-validator` for `readOnly` props. 
Ajv [knows this keywords](https://github.com/epoberezkin/ajv#annotation-keywords), but does not validate them, do you have an idea how to add a proper validation for this?
> openapi-response-validator: remove required writeOnly props from response validation

- packages/openapi-framework/index.ts
- packages/openapi-framework/src/util.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-consumes-requestbody-with-missing-ref/apiDoc.yml
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-consumes-requestbody-with-missing-ref/paths/foo.js
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-consumes-requestbody-with-missing-ref/spec.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-consumes-requestbody-with-ref/apiDoc.yml
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-consumes-requestbody-with-ref/paths/foo.js
- packages/openapi-framework/test/sample-projects/paths-dir-with-valid-method-consumes-requestbody-with-ref/spec.ts
- packages/openapi-framework/test/sample-projects/resolve-requestBody-reference-v3/apiDoc.yml
- packages/openapi-framework/test/sample-projects/resolve-requestBody-reference-v3/paths/foo.js
- packages/openapi-framework/test/sample-projects/resolve-requestBody-reference-v3/spec.ts
This resolves any `$ref` in the operation's `requestBody` prior to determining what media types are consumed and before passing the definition to the validator so that `components.requestBodies` can be used in v3 documents when using validation and/or `consumesMiddleware`. Prior to this change `$ref` in `requestBody` would silently be treated incorrectly due to assumptions on it being defined inline.
> openapi-framework: Add support for $ref in requestBody (closes #486)

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-a-charset-on-content-type.js
- Allow charset on content-type schemas for request body
Related #406
> fix(openapi-request-validator): allow charset on request content-type

- packages/openapi-request-validator/README.md
This fixes some errors of the example in the readme:
- outdated require statement
- missing curly braces
- unused version property
- spelling error in content property
- missing content-type header
> openapi-request-validator: fix example in readme (fixes #516)

- packages/openapi-jsonschema-parameters/index.ts
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema-openapi3.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-query-param-to-json-schema.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-nullable-complex-query-param-to-json-schema.js
npm v, 6.10.2
nodejs v. 12.8.1
-> I am not able to run the script on my 'Linux Mint'
On `> ./bin/test` I get `dev-tools/tsc` is a folder, it needs the `.sh` same with mocha, test, ...
After that I get 
```
openapi-jsonschema-parameters/test/data-driven.ts:5
import { convertParametersToJSONSchema } from '../';
^
SyntaxError: Unexpected token {
at Module._compile (internal/modules/cjs/loader.js:811:22)
```
-> `npm run lint` works but it looks like there are some errors in master
```
ERROR: packages/openapi-framework/index.ts:110:62 - Replace `⏎············arg.type⏎··········` with `arg.type`
ERROR: packages/openapi-framework/index.ts:122:75 - Replace `⏎············arg.className⏎··········` with `arg.className`
ERROR: packages/openapi-framework/index.ts:131:12 - Replace …
```
> openapi-jsonschema-parameters:  Adds 'examples' (fixes #513)

- packages/openapi-schema-validator/README.md
I updated the example in the README to fit the actual code:
https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-schema-validator/index.ts#L16-L17
> openapi-schema-validator: fix OpenAPISchemaValidatorArgs example

- packages/openapi-response-validator/index.ts
- packages/openapi-response-validator/test/data-driven/fail-with-unkown-status-code.js
make sure 'errors' is available on any error
alternative to https://github.com/kogosoftwarellc/open-api/pull/519 
`(openapi-response-validator and openapi-request-validator).validate` result will always contain 'errors[0].message' or undefined
> openapi-response-validator: add 'errors' on any error (fixes #512)

- packages/openapi-jsonschema-parameters/README.md
> remove extra parens from example code

- packages/openapi-default-setter/index.ts
- packages/openapi-default-setter/test/data-driven/set-defaults-from-query-and-header-schema.js
As described in the spec: https://swagger.io/docs/specification/describing-parameters/#query-parameters, parameter types are described using the `schema` property. The `default` property is defined under `parameter.schema.default`:
```
in: 'query',
name: 'someQuery',
schema: {
type: 'string',
default: 'someValue'
}
```
This PR implements support for this. But also keeps the support for reading the default value from the root level of the parameter object.
> openapi-default-setter: Support default values from schema property

- packages/express-openapi/README.md
Only a `readme` update, no code change.
> express-openapi: Fixes Typescript example to pick up `.ts` files

- packages/openapi-request-coercer/index.ts
This member is never set nor used.
> openapi-request-coercer: drop unused member

- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/coerce-array-with-style-openapi3.js
While working on #569, I stumbled on this which I believe is a typo (as the **[spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md)** never references it in the plural form).
> openapi-request-coercer: fix handling of OAS 3 explode

- .gitattributes
Normalize files line endings on check-in/check-out
cf. https://git-scm.com/docs/gitattributes
This change will ensure files in the repo will use keep on using LF as line terminators, while Windows developers will transparently get CRLF line terminators on checkout.
> Make xplat development experience a bit better

- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/package-lock.json
- packages/openapi-request-coercer/package.json
- packages/openapi-request-coercer/test/data-driven.ts
- packages/openapi-request-coercer/test/data-driven/ignore-unkown-types-openapi3.js
- packages/openapi-request-coercer/test/data-driven/ignore-unkown-types.js
- packages/openapi-request-coercer/test/data-driven/not-throw-on-untyped-array-params-in-request.js
Although defining the type of array items is required by the Swagger 2.0 spec, this is sadly not enforced by the schema. This change prevents the library from throwing in such case, by defaulting to an "identity" coercer.
References:
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject
- https://github.com/OAI/OpenAPI-Specification/blob/7ce374d67e46e2fdf0da49fc6e29f6854985627e/schemas/v2.0/schema.json#L1108-L1176
> openapi-request-coercer: do not throw on untyped array items

- packages/express-openapi/README.md
The forward slash "/" has to be escaped here.
> express-openapi: Added missing RegExp escape character in pathSecurity documentation

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/fail-requestBody-with-present-readOnly-property.js
ReadOnly properties should be present only in response. The request should reject them as those properties should not be modified.
JSON Schema Draft-07 brings new properties “readOnly”. That property allow to use conditional validation of object fields depending on context. That way the same schema definition could be re-use as part of post method where should be missing and get method where field is provided by server site. Here in openapi-request-validatior the context is always write, as we write data to server and all read only fields should be rejected.
> openapi-request-validatior: readOnly properties should be rejected

- packages/openapi-request-coercer/README.md
- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/custom-strategy-coercion.ts
> [WIP] openapi-request-coercer: accept custom coercion strategy

- packages/openapi-jsonschema-parameters/index.ts
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema-openapi3.js
> openapi-jsonschema-parameters: remove whitelisting of OpenAPI 3 schema validation keywords

- packages/openapi-types/index.ts
I hope you'll be happy with the lack of tests, as there don't appear to be tests in the openapi-types package!
> openapi-types: Add type constraint on SecuritySchemeOauth2Base (fixes #623)

- packages/openapi-types/index.ts
We have been happily using your open-api packages with great success on our js projects, thanks so much!  However, now that we are moving some things over to typescript we are hitting an issue that I've only been able to find documented in #126
This PR reintroduces those changes from #126 in a format that adheres to the PR guidelines.
> open-api-types: fix x-express-openapi-additional-middleware typings

- packages/openapi-types/index.ts
`OpenAPIV2.ResponseObject` should not require the `default` property.
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object where `default` is not marked as required.
> openapi-types: default response is optional

- packages/openapi-jsonschema-parameters/index.ts
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema-openapi3.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-query-param-to-json-schema.js
- packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-nullable-complex-query-param-to-json-schema.js
In json schema, the field `examples` is an array, but in openapi, that field is an object. To correctly support `examples`, convert `examples` to an array.
> openapi-jsonschema-parameters: Convert `examples` to an array (fixes #635)

- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/not-use-Object-prototype-entries-as-coercers.js
The coercion function iterates all enumerable properties on the request body and looks for a coercer function inside of the `coercers` object. However, because it checks the `coecers` object for the `paramName` using `in` it will also find entries on the Object prototype and treat them as coercer functions. The effect of this ranges from converting the `toString` function to a string of `[object Object]` to throwing a `TypeError` if a property is named `__defineSetter__`.
The way we discovered the issue was passing a Buffer as the request body (the result of running bodyParser.raw) and then attempting to convert it to base64.
> openapi-request-coercer: Fix function on Object.prototype being used as coercer

- packages/openapi-types/index.ts
OpenAPI Sepcification states that there is no `null` type. Also, to indicate a data model can be of any type, the `type` property can be omitted. I have removed `null` from the union type `NonArraySchemaObjectType` and changed `type: string` => `type?: string` in `NonArraySchemaObject`.
See https://swagger.io/docs/specification/data-models/data-types/
> openapi-types: Remove null type and make type property optional

- packages/koa-openapi/index.ts
the koa-router is able to generate URLs from named routes
this means if we use the operationId in the koa route
creation we can call `router.url` later with the operationId
and generate the URL as expected
For example, the OpenAPI operation
```
/foo/{foo_id}:
parameters
- name: foo_id
in: path
get:
operationId: bar
```
can be used with `route.url` as such:
```
const url = ctx.router.url('bar', { foo_id: 'hello' });
// `url` is "/foo/hello"
```
> koa-openapi: Name created routes for later use

- packages/koa-openapi/README.md
As the title says. The routes are created. Just not attached to the app. :-)
> README example wasn't linking routes to the app

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-nullable-on-allOf.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-nullable-on-anyOf.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-nullable-on-oneOf.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-value-on-nullable-on-allOf.js
```nullable: true``` validation didn't work on schemas like ```{
nullable: true,
allOf: [{ type: 'string' }]
}``` because there was no type-property.
This change handles allOf, anyOf, oneOf. Please see the added tests that would fail to validate the requests on null-values.
> openapi-request-validator: fix: nullability for allOf, anyOf, oneOf

- packages/openapi-framework/src/types.ts
Hello, 
Just noticed this error when trying to set `externalSchemas` with express-openapi in typescript. 
Typescript expects only one key in `externalSchemas` named "string" and I guess this isn't the intent:
```
src/index.ts:39:9 - error TS2322: Type '{ 'http://someurl.com/test': { description: string; type: string; properties: { name: { type: string; default: string; }; }; }; }' is not assignable to type '{ string: IJsonSchema; }'.
Object literal may only specify known properties, and ''http://someurl.com/test'' does not exist in type '{ string: IJsonSchema; }'.
```
> openapi-framework: Fix externalSchemas index type

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-object.js
This just handles the case in which your request body schema is a plain object and not a ref
> openapi-request-validator:  Fix readonly property for plain schema objects

- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/coerce-object-params-in-request-openapi3.js
OpenAPI 3.0 defines some serializations for objects/arrays in parameters. This implements support for the `deepObject` serialization by enabling coercers to be applied recursively based on the schema. 
The object serialization must still be enabled by the `enableObjectCoercion` flag, and if the style is not set to `deepObject`, then it uses the previous `JSON.parse` solution.
> openapi-request-coercer: Implement coercion for deepObject style parameters

- packages/express-openapi/README.md
- packages/express-openapi/test/sample-projects/with-customKeywords/api-doc.js
- packages/express-openapi/test/sample-projects/with-customKeywords/api-routes/coerce.js
- packages/express-openapi/test/sample-projects/with-customKeywords/app.js
- packages/express-openapi/test/sample-projects/with-customKeywords/spec.js
- packages/openapi-framework/index.ts
- packages/openapi-framework/src/types.ts
- packages/openapi-request-validator/index.ts
We use the added AJV customKeyword argument for type coercion in openapi-request-validator. This may fix #628?
This PR affects multiple packages so I made a single commit for every package. I hope that's the correct way?
Please review! :)
> Add support for customKeywords in openapi-request-validator

- packages/openapi-request-validator/index.ts
For an openapi `OperationObject`, the `parameters` property is optional:
https://github.com/kogosoftwarellc/open-api/blob/983a1c79e54e9bcef6eea43fe22615591c919aa1/packages/openapi-types/index.ts#L97
It would be useful for the equivalent parameter of the validator to be optional so that a valid operation can be easily passed to the validator.
> openapi-request-validator: Make `parameters` arg optional

- packages/openapi-response-validator/index.ts
With given `openapi-response-validator` initialization:
```ts
new OpenAPIResponseValidator({
responses: {…},
components: {…},
});
```
I'm getting following error:
```
Argument of type '{ responses: any; components: any; }' is not assignable to parameter of type 'OpenAPIResponseValidatorArgs'.
Type '{ responses: any; components: any; }' is missing the following properties from type 'OpenAPIResponseValidatorArgs':
customFormats, definitions, externalSchemas, loggingKey
```
However, as these keys are marked as optional in readme, they should be marked as optional in types, I believe.
I'm not sure why tests in the repository aren't failing with this error, hence no changes in tests.
> openapi-response-validator: Mark optional fields as optional in TypeScript types

- packages/openapi-types/CHANGELOG.md
- packages/openapi-types/index.ts
This change adds an index signature to the `openapi-types` package's `OperationObject` to allow access to OpenAPI extensions.
Additionally, `undefined` was added to the index signature on `PathsObject` to ensure safe access when `strictNullChecks` is enabled.
> openapi-types: Add safe extension access.

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-components-property-ref.js
- packages/openapi-request-validator/test/data-driven/accept-requestBody-with-definitions-property-ref-v3.js
Hello!
I am opening this PR to add the ability to validate schemas that reference properties of object schema definitions.
```json
{
"paths": {
"/login": {
"requestBody": {
"content": {
"application/json": {
"schema": {
"type": "object",
"properties": {
"login": {
"oneOf": [
{
"$ref": "#/components/schemas/User/properties/username"
},
{
"$ref": "#/components/schemas/User/properties/email"
}
]
},
"password": {
"$ref": "#/components/schemas/schemas/User/properties/password"
}
}
}
}
},
"required": true
}
}
},
"components": {
"schemas": {
"User": {
"type": "object",
"properties": {
"id": {
"type": "string"
},
"username": {
"type": "string"
},
"email": {
"type": "string",
"format": "email"
},
"password": {
"type": "string",
"minLength": 8
},
"data": {
"oneOf": [
{
"type": "object", …
```
> openapi-request-validator: Add ability to validate schemas that references schema object properties.

- packages/openapi-request-validator/index.ts
This PR allow pass extra options to Ajv validator for example to enable `removeAdditional`.
> openapi-request-validator: add ajv options (fixes #65)

- packages/express-openapi/test/sample-projects/with-openapiv3-formdata-params/api-doc.yml
- packages/express-openapi/test/sample-projects/with-openapiv3-formdata-params/api-routes/test.js
- packages/express-openapi/test/sample-projects/with-openapiv3-formdata-params/app.js
- packages/express-openapi/test/sample-projects/with-openapiv3-formdata-params/spec.js
- packages/koa-openapi/test/sample-projects/with-openapiv3-formdata-params/api-doc.yml
- packages/koa-openapi/test/sample-projects/with-openapiv3-formdata-params/api-routes/test.js
- packages/koa-openapi/test/sample-projects/with-openapiv3-formdata-params/app.js
- packages/koa-openapi/test/sample-projects/with-openapiv3-formdata-params/spec.js
- packages/openapi-framework/index.ts
- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/coerce-form-data-openapi3.js
- **openapi-request-coercer: Support oapiv3 formdata**
In OpenAPI v3, formData requests are specified using the
'application/x-www-form-urlencoded' content-type inside the
`requestBody` section of the operation. This commit adds support for
coercing those formData parameters.
- **openapi-framework: Pass requestBody to coercer**
In OpenAPIv3, formData is specified as a part of the `requestBody` field
of the operation. This commit passes the `requestBody` to the coercer so
that it can pull the formData parameters out and coerce them.
Related to #710.
> coerce formdata openapiv3

- packages/openapi-types/index.ts
If I want programmatically inspect or preprocess spec, then I'm in trouble when I want to iterate over all possible HTTP methods inside every path, I have to duplicate list of HTTP from [spec's `PathItemObject`](https://swagger.io/specification/#path-item-object) verbs in my code, and after that TypeScript will throw an error because it can't figure out that all of array elements are declared in `PathItemObject` type definition:
```typescript
import { OpenAPIV3 } from "openapi-types"
const apiSpec: <OpenAPIV3.Document> = { … }
for (const methods of Object.values(schema.paths)) {
for (const method of ["get", "post", "put", "delete", "options", "head", "patch", "trace"]) {
const pathItem = methods[method] // ERROR!
//               ~~~~~~~~~~~~~~~
// Element implicitly has an 'any' type …
```
> openapi-types: Extract HTTP methods to enum to allow programmatic access

- packages/openapi-security-handler/index.ts
Please allow openapi v3 to be specified in the security scheme.
> openapi-security-handler: security scheme allow openapi 3.x

- packages/openapi-types/index.ts
> openapi-types: remove 'any' type from OpenApiV2.Document.paths[idx] typing (fixes #552)

- package-lock.json
- package.json
- packages/openapi-schema-validator/index.ts
- packages/openapi-schema-validator/package-lock.json
- packages/openapi-schema-validator/package.json
- packages/openapi-schema-validator/resources/openapi-2.0.json
- packages/openapi-schema-validator/resources/openapi-3.0.json
- packages/openapi-schema-validator/test/data-driven/fail-invalid-v2-documents.js
- packages/openapi-schema-validator/test/data-driven/fail-invalid-v3-documents.js
part 1 for issue #727 
AJV v6 is no longer receiving feature updates and stops receiving security updates at the end of June. AJV v6 also has an outstanding security issue (in issue).
AJV v8 does not support json schema draft 4, so along with upgrading to ajv 8, we need to switch to json schema draft 7.
I could not find the repo for openapi schema v2, so I've removed the npm dependency and included the file here to upgrade the schema to draft 7.
New typescript version is needed for the newer version of AJV
> openapi-schema-validator: upgrade ajv to version 8 and use json schema draft 7

- packages/express-openapi/index.ts
- packages/express-openapi/package-lock.json
fixes the imports for ajv v8 included by @types/ajv for #727
> express-openapi: upgrade to ajv v8 types imported

- packages/openapi-types/index.ts
- packages/openapi-types/tsconfig.json
fixes #742
This PR enables strict mode for typescript.
Impressively, the project only has one issue that doesn't work in strict mode, and this PR also fixes that.
You can check this quickly by running `npx lerna run prepare` which eventually runs `tsc`.
Strict mode (and this fix) is required by our project which depends directly on `openapi-types`, so your review of this and eventual release is much appreciated.
- not explicitly a test, but `npx lerna run prepare` will demonstrate that the strict compilation works properly
> openapi-type: strictly define `ResponsesObject` type

- packages/openapi-types/index.ts
According to:
- https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0
- https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released
- https://spec.openapis.org/oas/v3.1.0
I've prepared types for OpenApi 3.1 support.
Don't know if we would like to keep OA 3.0 types, so i decided to keep under another namespace.
I've changed types mostly by extending types from OA 3.0, but in many cases there are some changes.
Looking for some feedback from You, I know this also need to write some tests (I will write as soon as possible, or maybe someone would like to help?)
> openapi-types: adding support for openapi 3.1

- packages/koa-openapi/index.ts
Make `docsPath`, `errorMiddleware`, `exposeApiDocs` & `securityFilter` options optional.
In accordance to `express-openapi` & the framework itself: https://github.com/kogosoftwarellc/open-api/blob/13ad704b645055d9baec6e047a2d1a1288edb538/packages/express-openapi/index.ts#L27-L35
> [koa-openapi]: update `initialize` options

- packages/express-openapi/test/sample-projects/basic-usage-with-central-apiDoc/app.js
- packages/express-openapi/test/sample-projects/basic-usage-with-central-apiDoc/spec.js
- packages/openapi-framework/index.ts
- packages/openapi-framework/test/sample-projects/operations-dir-with-middleware/apiDoc.yml
- packages/openapi-framework/test/sample-projects/operations-dir-with-middleware/operations/foo.js
- packages/openapi-framework/test/sample-projects/operations-dir-with-middleware/paths/foo.js
- packages/openapi-framework/test/sample-projects/operations-dir-with-middleware/spec.ts
The goal of this PR is to bring the functionality of `args.operations` up to speed with how `args.paths` works with regards to middleware.
While args.paths (autoload like functionality) allows you to expose an array of middleware as an operation handler, the args.operations requires that the operation handler be a function. Attempting to pass an array result in a `TypeError`
```
/path/to/project/node_modules/openapi-framework/dist/index.js:165
return innerFunction.bind({
^
TypeError: innerFunction.bind is not a function
```
I believe this was first documented in #618, and can make mounting middleware awkward or impossible at times.  
This PR is may me incomplete. **If** the maintainers are open to a change like this, then I'd love to take it across the finish line. However, since I'm …
> openapi-framework: add middleware for operations

- packages/koa-openapi/index.ts
- packages/koa-openapi/test/sample-projects/with-securityHandlers/api-doc.js
- packages/koa-openapi/test/sample-projects/with-securityHandlers/api-routes/boo.js
- packages/koa-openapi/test/sample-projects/with-securityHandlers/api-routes/fail.js
- packages/koa-openapi/test/sample-projects/with-securityHandlers/api-routes/foo.js
- packages/koa-openapi/test/sample-projects/with-securityHandlers/app.js
- packages/koa-openapi/test/sample-projects/with-securityHandlers/spec.js
Depends on #772.
As the title of #286 says, "Security checks run after data (body/params) validation".
This issue exposed the problem, was fixed for express in [PR 288](https://github.com/kogosoftwarellc/open-api/pull/288/files), but a fix was not included for koa.
This fixes it.
> [koa-openapi] fix koa security middleware order (fixes #286 for koa)

- packages/express-openapi/test/sample-projects/with-multiple-operations-sharing-the-same-controller/api-doc.json
- packages/express-openapi/test/sample-projects/with-multiple-operations-sharing-the-same-controller/app.js
- packages/express-openapi/test/sample-projects/with-multiple-operations-sharing-the-same-controller/spec.js
- packages/openapi-framework/index.ts
- packages/openapi-framework/test/sample-projects/missing-operation-id/spec.ts
- packages/openapi-framework/test/sample-projects/operations-dir-with-valid-methid-doc-after-dependency-injection/apiDoc.yml
- packages/openapi-framework/test/sample-projects/operations-dir-with-valid-methid-doc-after-dependency-injection/spec.ts
This PR implements possible solution 1️⃣   from #778 which is a bug that was introduced in #769
It restores behavior of binding the operation, or (new behavior) by binding each middleware in the array.
I think it is worth some discussion about if this is the _correct_ fix and hopefully this can help kick start the conversation.
~All tests are currently passing, but linting is not. Just need to make some small tweaks to make prettier happy.~
> BugFix: #778 dont overwrite api doc when controller is shared

- packages/openapi-framework/src/types.ts
Hello, small change to the typing of the `operations` attribute in order for it to be aligned with the changes in https://github.com/kogosoftwarellc/open-api/pull/769.
No breaking change as it simply adds the array as an additional type.
Thank you 🙂
> openapi-framework: fix typing operations (allow array)

- packages/openapi-framework/index.ts
- packages/openapi-framework/src/util.ts
- packages/openapi-framework/test/sample-projects/missing-operation-id/spec.ts
- packages/openapi-framework/test/sample-projects/operations-empty/apiDoc.yml
- packages/openapi-framework/test/sample-projects/operations-empty/spec.ts
This PR tried to resolve
#722 : It would be
nice to be able to use openapi-framework without an implementation, e.g.
to implement generic request validation.
Looking a the code it seem to have worked in the past, as
routeItem.operations rather looks like a typo.
> openapi-framework: Allow usage without implementation

- packages/openapi-framework/index.ts
- packages/openapi-framework/src/types.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/apiDoc.yml
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/features/CustomCoercer.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/features/CustomDefaultSetter.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/features/CustomRequestValidator.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/features/CustomResponseValidator.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/features/CustomSecurityHandler.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/paths/foo.js
- packages/openapi-framework/test/sample-projects/paths-dir-with-custom-features/spec.ts
- packages/openapi-framework/test/sample-projects/paths-dir-with-default-features/apiDoc.yml
- packages/openapi-framework/test/sample-projects/paths-dir-with-default-features/paths/foo.js
- packages/openapi-framework/test/sample-projects/paths-dir-with-default-features/spec.ts
The current implementation does not allow defining custom classes to be used for:
* defaults setting
* coercing
* request/response validation
* security handlers
This is absolutely fine for the general use case. 
However, in very large projects this incurs a fairly large penalty on startup. For example, to perform an integration test on a single endpoint all of the classes must be instantiated for all paths/operations.
Allowing consumers to inject their own instances of these classes will support behavior like, within test environments, providing thin wrappers around the existing classes for this functionality which are lazy-initialized on any property being accessed. Lazy-initializing these classes sees fairly large improvements in integration test times for large API documents.
This may …
> openapi-framework: Allow injecting custom classes for features

- packages/openapi-request-coercer/index.ts
- packages/openapi-request-coercer/test/data-driven/coerce-headers-case-insensitive.js
Header field names are case insensitive which was addressed to some extent in the code by lowercasing the properties of the `coercers` object ([here](https://github.com/kogosoftwarellc/open-api/blob/5c68224a2e85bc1a55c7a6aa29c30e5d0f873032/packages/openapi-request-coercer/index.ts#L137) via the [`l` helper function](https://github.com/kogosoftwarellc/open-api/blob/5c68224a2e85bc1a55c7a6aa29c30e5d0f873032/packages/openapi-request-coercer/index.ts#L118)). However, the function performing the coercion compared the original (non-lowercase) fields to the lowercase coercers properties ([here](https://github.com/kogosoftwarellc/open-api/blob/5c68224a2e85bc1a55c7a6aa29c30e5d0f873032/packages/openapi-request-coercer/index.ts#L143)), which doesn't work unless the header was lowercase to begin with. …
> openapi-request-coercer: fix header coercing

- packages/openapi-request-validator/index.ts
- packages/openapi-request-validator/test/data-driven/accept-case-insensitive-content-type-header.js
HTML headers are lowercase most of the time, but some applications (eg:AWS) may use a different case. In such cases headers like `content-type` can be sent as `Content-Type`. 
The request validator is written to throw an error when the request body is required AND  `content-type` header is not present. Currently this error is thrown if `content-type` header is not in lowercase. 
This fixes this issue and **makes the content-type header case-insensitive**
> openapi-request-validator: make mimetype header case insensitive

- packages/openapi-types/index.ts
The `OAuth2SecurityScheme` typescript interface is missing an optional `description` field, that other security schemes have present. According to the [specification](https://swagger.io/specification/) it can be present in any of the security schemes.
> openapi-types: Add optional description field to oauth security scheme

- .github/workflows/pr.yml
- packages/openapi-framework/index.ts
Re https://github.com/kogosoftwarellc/open-api/issues/812
Always add the `file://` prefix when loading ES moduls or CommonJS scripts.
Tested with:
```sh
npm run bootstrap
cd packages/express-openapi
npm run test
```
> add absolute file prefix for dynamic imports

- packages/openapi-types/index.ts
The "const" keyword was added in OAS 3.1, largely as syntactic sugar for a single value enum. It's been a part of the JSON schema spec since draft-06 and seems to be more common out in the wild now.
> openapi-types: Add support for "const" keyword to base schema type.

- packages/express-openapi/README.md
Somehow a high Unicode character snuck in where normal ASCII was preferred.
> express-openapi : Change non-breaking hyphen char to unicode to simple dash

- .github/workflows/pr.yml
> Testing coveralls

- packages/openapi-types/index.ts
Currently, you only accept a string as a value default value type, but a number is also allowed (eg. for a port number) in OpenAPI.
Numbers are also an accepted type here! Example use-case:
```ts
servers: [
{
url: 'http://localhost:{port}/{basePath}',
description: 'Development server',
variables: {
port: {
default: 3001
},
basePath: {
default: 'api/v1'
}
}
}
````
> openapi-types: A number is also allowed for a server variable value
