kogosoftwarellc/open-api

index.js, package.json, test/fixtures/with-external-schema-references-api-doc-after-initialization.json, test/initialization.js, test/sample-projects.js, test/sample-projects/with-external-schema-references/api-doc.js, test/sample-projects/with-external-schema-references/api-routes/users.js, test/sample-projects/with-external-schema-references/api-routes/users/{userId}.js, test/sample-projects/with-external-schema-references/app.js, typings/express-openapi/express-openapi.d.ts
See #17 
This works after following PRs are merged & published as new versions and update package.json.
https://github.com/kogosoftwarellc/express-openapi-response-validation/pull/2
https://github.com/kogosoftwarellc/express-openapi-validation/pull/3
=> Support external schema reference

README.md
=> Update readme adding external schema reference and express app mount

README.md, index.js, package.json, test/initialization.js, test/sample-projects.js, test/sample-projects/with-securityHandlers/api-doc.js, test/sample-projects/with-securityHandlers/api-routes/boo.js, test/sample-projects/with-securityHandlers/api-routes/fail.js, test/sample-projects/with-securityHandlers/api-routes/foo.js, test/sample-projects/with-securityHandlers/app.js
@MugeSo can you review this?  I'm wondering what the best way to handle scope is (I've never even used scopes before so any info you can give me would be great).
=> Adding args.securityHandlers.

typings/express-openapi/express-openapi.d.ts
hi,
I updated typings to follow latest :)
=> typings: add consumesMiddleware, pathSecurity support

index.js, test/sample-projects/with-multiple-named-parameter-in-a-path-part/api-doc.js, test/sample-projects/with-multiple-named-parameter-in-a-path-part/api-routes/users/{id}@{org}.js, test/sample-projects/with-multiple-named-parameter-in-a-path-part/api-routes/{region}-{az}/{id}.js, test/sample-projects/with-multiple-named-parameter-in-a-path-part/api-routes/{region}-{az}/{id}.{type}.js, test/sample-projects/with-multiple-named-parameter-in-a-path-part/app.js, test/sample-projects/with-multiple-named-parameter-in-a-path-part/spec.js
This PR allows `/{foo}-{bar}/{file}.{ext}`
=> Allow multiple named parameter in single path part

packages/express-openapi/README.md
=> File upload example for express README

packages/express-openapi/package.json
=> fix(package): update openapi-response-validator to version 1.0.2

packages/express-openapi/README.md
readFilesync -> readFileSync on line 270
=> Typo in readme

package-lock.json, package.json, packages/openapi-types/package.json
* Adding a test-watch script to openapi-types
=> Updating @types/node to 10.9.4.

.npmignore, packages/express-openapi/CHANGELOG.md, packages/express-openapi/package-lock.json, packages/express-openapi/package.json, packages/express-openapi/test/sample-projects/file-upload/api-doc.js, packages/express-openapi/test/sample-projects/file-upload/api-routes/fileupload.js, packages/express-openapi/test/sample-projects/file-upload/app.js, packages/express-openapi/test/sample-projects/file-upload/spec.js, packages/openapi-framework/CHANGELOG.md, packages/openapi-framework/package-lock.json, packages/openapi-framework/package.json, packages/openapi-jsonschema-parameters/CHANGELOG.md, packages/openapi-jsonschema-parameters/index.ts, packages/openapi-jsonschema-parameters/package-lock.json, packages/openapi-jsonschema-parameters/package.json, packages/openapi-jsonschema-parameters/test/data-driven/not-convert-file-type.js, packages/openapi-request-validator/CHANGELOG.md, packages/openapi-request-validator/package-lock.json, packages/openapi-request-validator/package.json, packages/openapi-request-validator/test/data-driven/accept-file-type-parameters.js, packages/openapi-schema-validator/test/data-driven/accept-valid-v2-documents.js
cc @troymolsberry @danilameister
=> Fixing file type

packages/openapi-request-validator/README.md, packages/openapi-request-validator/index.ts, packages/openapi-request-validator/test/data-driven/accept-requestBody.js, packages/openapi-request-validator/test/data-driven/fail-unsupported-media-type-for-request-body.js, packages/openapi-request-validator/test/data-driven/use-given-media-type-schema-for-requestBody.js
This is a step toward resolving #162 
My approach was to try to keep it backwards compatible, but I imagine that there could be a couple of different approaches to handling v3, so I'm hoping this at least starts the conversation.
=> Request validator request body

packages/openapi-framework/index.ts, packages/openapi-framework/test/sample-projects/validate-requestbody-no-parameters/apiDoc.yml, packages/openapi-framework/test/sample-projects/validate-requestbody-no-parameters/paths/foo.js, packages/openapi-framework/test/sample-projects/validate-requestbody-no-parameters/spec.ts
https://github.com/kogosoftwarellc/open-api/issues/294
=> Bugfix for issue #294

packages/openapi-jsonschema-parameters/index.ts, packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema-openapi3.js
=> openapi-jsonschema-parameters : headers, formdata and path parameters validation for openapi3

packages/openapi-response-validator/README.md, packages/openapi-response-validator/package.json
closes https://github.com/kogosoftwarellc/open-api/issues/316
=> fix github url and constructor typo

package.json
=> tslint fix: it doesnt read the config tslint.json unless specified

packages/express-openapi/README.md, packages/express-openapi/package-lock.json, packages/express-openapi/package.json, packages/express-openapi/test/sample-projects/with-consumes-middleware-multipart-openapi3/api-doc.js, packages/express-openapi/test/sample-projects/with-consumes-middleware-multipart-openapi3/api-routes/multiple-attachments.js, packages/express-openapi/test/sample-projects/with-consumes-middleware-multipart-openapi3/api-routes/single-attachment.js, packages/express-openapi/test/sample-projects/with-consumes-middleware-multipart-openapi3/api-routes/with-text-fields.js, packages/express-openapi/test/sample-projects/with-consumes-middleware-multipart-openapi3/app.js, packages/express-openapi/test/sample-projects/with-consumes-middleware-multipart-openapi3/spec.js
@jsdevel This is the Readme update you requested, along with all the tests I could think of. If you think the tests are too much (they add a dev dependency for `multer`), I can remove them. Let me know your thoughts!
=> express-openapi: Test for OpenApi3 Multipart Form consumes middleware

packages/openapi-framework/index.ts, packages/openapi-framework/src/types.ts, packages/openapi-framework/src/util.ts
follow up on https://github.com/kogosoftwarellc/open-api/pull/322
=> openapi-framework: replace console with Logger (#61)

packages/openapi-request-coercer/index.ts, packages/openapi-request-coercer/test/data-driven/coerce-number-params.js
=> Don't coerce into numbers values that cannot be converted (issue #371)

.travis.yml, packages/express-openapi/index.ts, packages/express-openapi/test/sample-projects/without-basePath-and-different-docsPath/spec.js, packages/koa-openapi/index.ts, packages/koa-openapi/package.json, packages/koa-openapi/test/sample-projects/without-basePath/api-doc.js, packages/koa-openapi/test/sample-projects/without-basePath/app.js, packages/koa-openapi/test/sample-projects/without-basePath/spec.js
=> express-openapi: Set default basePath (issue #376)

packages/openapi-request-validator/index.ts, packages/openapi-request-validator/test/data-driven/accept-requestBody-with-components-default.js
=> openapi-request-validator: Set "useDefaults: true" on Ajv

packages/openapi-request-validator/index.ts
A console log that should not be there :S
Closes #448
=> openapi-request-validator: remove console log

packages/openapi-jsonschema-parameters/index.ts, packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema-openapi3.js, packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-path-parameter-to-json-schema.js, packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-complex-query-param-to-json-schema.js, packages/openapi-jsonschema-parameters/test/data-driven/convert-a-single-nullable-complex-query-param-to-json-schema.js
closes https://github.com/kogosoftwarellc/open-api/issues/455
=> Adds 'example' validation keyword for openapi-jsonschema-parameters

package-lock.json, package.json
=> Greenkeeper/@types/node 12.0.8

packages/express-openapi/index.ts
=> Fix OperationHandlerArray interface

packages/openapi-request-validator/index.ts, packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-deeply-nested.js
solves issue of https://github.com/kogosoftwarellc/open-api/pull/472
=> openapi-request-validator: fixes circular $ref

.editorconfig
- Add support for typescript files
- Remove trailing whitespaces
- Enforce a final newline at the end of each file
=> Widen editorconfig settings

packages/openapi-request-validator/index.ts, packages/openapi-request-validator/test/data-driven/accept-requestBody-with-missing-readonly-required-property-deeply-nested.js
=> openapi-request-validator: fixes circular $ref for items

.npmignore
Recent versions of all the packages have been shipped with an artifact `tsc` produces, I'm assuming you didn't want to ship with that as it's useless to have it in the package. I'm also not very familiar with lerna so I hope this works.
=> Ignore TS build artifact

packages/openapi-types/index.ts
=> openapi-types: use generics for OpenAPI extensions handling

packages/express-openapi/README.md
fixes #676 
https://github.com/OAI/OpenAPI-Specification/tree/master/schemas/v3.0
=> README.md: update due to OpenAPI v3.0 has been released

packages/express-openapi/test/sample-projects/with-apiDoc-parameters-and-responses/spec.js, packages/express-openapi/test/sample-projects/with-customFormats/spec.js, packages/express-openapi/test/sample-projects/with-external-schema-references/spec.js, packages/openapi-response-validator/index.ts, packages/openapi-response-validator/package-lock.json, packages/openapi-response-validator/package.json, packages/openapi-response-validator/test/data-driven/fail-any-response-with-undefined-schema.js, packages/openapi-response-validator/test/data-driven/fail-customFormats.js, packages/openapi-response-validator/test/data-driven/fail-invalid-response.js, packages/openapi-response-validator/test/data-driven/fail-response-against-undefined-schema.js, packages/openapi-response-validator/test/data-driven/fail-unexpected-empty-response.js, packages/openapi-response-validator/test/data-driven/fail-with-definition-references.js, packages/openapi-response-validator/test/data-driven/fail-with-external-references-through-local-ref.js, packages/openapi-response-validator/test/data-driven/fail-with-external-references-with-path-through-local-ref.js, packages/openapi-response-validator/test/data-driven/fail-with-external-references-with-path.js, packages/openapi-response-validator/test/data-driven/fail-with-external-references.js
part of #727 (see checklist in issue of all changes from ajv6 -> ajv8)
=> openapi-response-validator: upgrade to ajv version 8 for json schema 7 compatibility

packages/openapi-types/index.ts
=> Add pathsobject v3 extension

packages/openapi-types/index.ts
=> openapi-types: updated `OperationObject` to match spec

packages/openapi-types/README.md
=> openapi-types: adding openapi 3.1 support to readme

packages/koa-openapi/index.ts
=> koa-openapi: forward rejection from securityMiddleware (fixes #603)

packages/openapi-types/index.ts
=> allow schema of MediaTypeObject to be a ReferenceObject as well

packages/openapi-request-validator/index.ts, packages/openapi-request-validator/test/data-driven/accept-an-additional-query-param.js, packages/openapi-request-validator/test/data-driven/fail-an-additional-query-param.js
=> openapi-request-validator: add additionalQueryProperties option (#795)

bin/update-deps, packages/fetch-openapi/package-lock.json, packages/fs-routes/package-lock.json, packages/koa-openapi/package-lock.json, packages/openapi-default-setter/package-lock.json, packages/openapi-framework/package-lock.json, packages/openapi-jsonschema-parameters/package-lock.json, packages/openapi-request-coercer/package-lock.json, packages/openapi-request-validator/package-lock.json, packages/openapi-response-validator/package-lock.json, packages/openapi-schema-validator/package-lock.json, packages/openapi-security-handler/package-lock.json, packages/openapi-types/package-lock.json, packages/restify-openapi/package-lock.json
=> fixes #801: Updating security vulnerabilities

packages/openapi-types/index.ts
=> Fix Typescrpt 4.8 incompatiblity

.github/workflows/main.yml
=> Adding main build
